language: ruby

rvm:
  - 2.0.0
  - 2.1.1

script:
  - bundle exec rake chef:foodcritic

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#linyows"
